name: cashier_system
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  http: ^1.2.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  # Responsive:
  responsive_builder: ^0.7.0
  flutter_screenutil: ^5.9.0
  window_manager: ^0.3.8
  #image / icons / svg:
  flutter_svg: ^2.0.10+1
  lottie: ^3.0.0
  # Widgets:
  drop_down_list: ^0.0.5
  floating_bubbles: ^2.6.2
  file_picker: ^6.2.0
  cached_network_image: ^3.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/icons/  
